version: '3.8'

services:
  mastodon-groupy-bot:
    image: python:3.8-slim
    container_name: mastodon-groupy-bot
    volumes:
      - ./bot.py:/app/bot.py
      - ./config.toml:/app/config.toml
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    command: ["bash", "-c", "pip install -r requirements.txt && python bot.py"]
    restart: on-failure
    tty: true
    stdin_open: true
